fragment DropParts on Drop {
  __typename
  title
  theme
  publishDate
  confirmationDeadline
  deliveryWindow
  description
  bottles {
    __typename
    name
    producer
    region
    vintage
    colour
    isInvestment
  }
}

fragment WinedropParts on Winedrop {
  __typename
  title
  intro
  faqs {
    __typename
    question
    answer
  }
  closing
}
