//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  drop: Drop;
  dropConnection: DropConnection;
  winedrop: Winedrop;
  winedropConnection: WinedropConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDropArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDropConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DropFilter>;
};


export type QueryWinedropArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryWinedropConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<WinedropFilter>;
};

export type DocumentFilter = {
  drop?: InputMaybe<DropFilter>;
  winedrop?: InputMaybe<WinedropFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Drop | Winedrop | Folder;

export type DropBottles = {
  __typename?: 'DropBottles';
  name: Scalars['String']['output'];
  producer?: Maybe<Scalars['String']['output']>;
  region?: Maybe<Scalars['String']['output']>;
  vintage?: Maybe<Scalars['String']['output']>;
  colour?: Maybe<Scalars['String']['output']>;
  isInvestment?: Maybe<Scalars['Boolean']['output']>;
};

export type Drop = Node & Document & {
  __typename?: 'Drop';
  title: Scalars['String']['output'];
  theme?: Maybe<Scalars['String']['output']>;
  publishDate: Scalars['String']['output'];
  confirmationDeadline?: Maybe<Scalars['String']['output']>;
  deliveryWindow?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['JSON']['output']>;
  bottles?: Maybe<Array<Maybe<DropBottles>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type DropBottlesFilter = {
  name?: InputMaybe<StringFilter>;
  producer?: InputMaybe<StringFilter>;
  region?: InputMaybe<StringFilter>;
  vintage?: InputMaybe<StringFilter>;
  colour?: InputMaybe<StringFilter>;
  isInvestment?: InputMaybe<BooleanFilter>;
};

export type DropFilter = {
  title?: InputMaybe<StringFilter>;
  theme?: InputMaybe<StringFilter>;
  publishDate?: InputMaybe<DatetimeFilter>;
  confirmationDeadline?: InputMaybe<DatetimeFilter>;
  deliveryWindow?: InputMaybe<StringFilter>;
  description?: InputMaybe<RichTextFilter>;
  bottles?: InputMaybe<DropBottlesFilter>;
};

export type DropConnectionEdges = {
  __typename?: 'DropConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Drop>;
};

export type DropConnection = Connection & {
  __typename?: 'DropConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DropConnectionEdges>>>;
};

export type WinedropFaqs = {
  __typename?: 'WinedropFaqs';
  question: Scalars['String']['output'];
  answer: Scalars['String']['output'];
};

export type Winedrop = Node & Document & {
  __typename?: 'Winedrop';
  title: Scalars['String']['output'];
  intro?: Maybe<Scalars['String']['output']>;
  faqs?: Maybe<Array<Maybe<WinedropFaqs>>>;
  closing?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type WinedropFaqsFilter = {
  question?: InputMaybe<StringFilter>;
  answer?: InputMaybe<StringFilter>;
};

export type WinedropFilter = {
  title?: InputMaybe<StringFilter>;
  intro?: InputMaybe<StringFilter>;
  faqs?: InputMaybe<WinedropFaqsFilter>;
  closing?: InputMaybe<StringFilter>;
};

export type WinedropConnectionEdges = {
  __typename?: 'WinedropConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Winedrop>;
};

export type WinedropConnection = Connection & {
  __typename?: 'WinedropConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<WinedropConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateDrop: Drop;
  createDrop: Drop;
  updateWinedrop: Winedrop;
  createWinedrop: Winedrop;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateDropArgs = {
  relativePath: Scalars['String']['input'];
  params: DropMutation;
};


export type MutationCreateDropArgs = {
  relativePath: Scalars['String']['input'];
  params: DropMutation;
};


export type MutationUpdateWinedropArgs = {
  relativePath: Scalars['String']['input'];
  params: WinedropMutation;
};


export type MutationCreateWinedropArgs = {
  relativePath: Scalars['String']['input'];
  params: WinedropMutation;
};

export type DocumentUpdateMutation = {
  drop?: InputMaybe<DropMutation>;
  winedrop?: InputMaybe<WinedropMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  drop?: InputMaybe<DropMutation>;
  winedrop?: InputMaybe<WinedropMutation>;
};

export type DropBottlesMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  producer?: InputMaybe<Scalars['String']['input']>;
  region?: InputMaybe<Scalars['String']['input']>;
  vintage?: InputMaybe<Scalars['String']['input']>;
  colour?: InputMaybe<Scalars['String']['input']>;
  isInvestment?: InputMaybe<Scalars['Boolean']['input']>;
};

export type DropMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  theme?: InputMaybe<Scalars['String']['input']>;
  publishDate?: InputMaybe<Scalars['String']['input']>;
  confirmationDeadline?: InputMaybe<Scalars['String']['input']>;
  deliveryWindow?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['JSON']['input']>;
  bottles?: InputMaybe<Array<InputMaybe<DropBottlesMutation>>>;
};

export type WinedropFaqsMutation = {
  question?: InputMaybe<Scalars['String']['input']>;
  answer?: InputMaybe<Scalars['String']['input']>;
};

export type WinedropMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  intro?: InputMaybe<Scalars['String']['input']>;
  faqs?: InputMaybe<Array<InputMaybe<WinedropFaqsMutation>>>;
  closing?: InputMaybe<Scalars['String']['input']>;
};

export type DropPartsFragment = { __typename: 'Drop', title: string, theme?: string | null, publishDate: string, confirmationDeadline?: string | null, deliveryWindow?: string | null, description?: any | null, bottles?: Array<{ __typename: 'DropBottles', name: string, producer?: string | null, region?: string | null, vintage?: string | null, colour?: string | null, isInvestment?: boolean | null } | null> | null };

export type WinedropPartsFragment = { __typename: 'Winedrop', title: string, intro?: string | null, closing?: string | null, faqs?: Array<{ __typename: 'WinedropFaqs', question: string, answer: string } | null> | null };

export type DropQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type DropQuery = { __typename?: 'Query', drop: { __typename: 'Drop', id: string, title: string, theme?: string | null, publishDate: string, confirmationDeadline?: string | null, deliveryWindow?: string | null, description?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, bottles?: Array<{ __typename: 'DropBottles', name: string, producer?: string | null, region?: string | null, vintage?: string | null, colour?: string | null, isInvestment?: boolean | null } | null> | null } };

export type DropConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DropFilter>;
}>;


export type DropConnectionQuery = { __typename?: 'Query', dropConnection: { __typename?: 'DropConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'DropConnectionEdges', cursor: string, node?: { __typename: 'Drop', id: string, title: string, theme?: string | null, publishDate: string, confirmationDeadline?: string | null, deliveryWindow?: string | null, description?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, bottles?: Array<{ __typename: 'DropBottles', name: string, producer?: string | null, region?: string | null, vintage?: string | null, colour?: string | null, isInvestment?: boolean | null } | null> | null } | null } | null> | null } };

export type WinedropQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type WinedropQuery = { __typename?: 'Query', winedrop: { __typename: 'Winedrop', id: string, title: string, intro?: string | null, closing?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, faqs?: Array<{ __typename: 'WinedropFaqs', question: string, answer: string } | null> | null } };

export type WinedropConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<WinedropFilter>;
}>;


export type WinedropConnectionQuery = { __typename?: 'Query', winedropConnection: { __typename?: 'WinedropConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'WinedropConnectionEdges', cursor: string, node?: { __typename: 'Winedrop', id: string, title: string, intro?: string | null, closing?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, faqs?: Array<{ __typename: 'WinedropFaqs', question: string, answer: string } | null> | null } | null } | null> | null } };

export const DropPartsFragmentDoc = gql`
    fragment DropParts on Drop {
  __typename
  title
  theme
  publishDate
  confirmationDeadline
  deliveryWindow
  description
  bottles {
    __typename
    name
    producer
    region
    vintage
    colour
    isInvestment
  }
}
    `;
export const WinedropPartsFragmentDoc = gql`
    fragment WinedropParts on Winedrop {
  __typename
  title
  intro
  faqs {
    __typename
    question
    answer
  }
  closing
}
    `;
export const DropDocument = gql`
    query drop($relativePath: String!) {
  drop(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...DropParts
  }
}
    ${DropPartsFragmentDoc}`;
export const DropConnectionDocument = gql`
    query dropConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: DropFilter) {
  dropConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...DropParts
      }
    }
  }
}
    ${DropPartsFragmentDoc}`;
export const WinedropDocument = gql`
    query winedrop($relativePath: String!) {
  winedrop(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...WinedropParts
  }
}
    ${WinedropPartsFragmentDoc}`;
export const WinedropConnectionDocument = gql`
    query winedropConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: WinedropFilter) {
  winedropConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...WinedropParts
      }
    }
  }
}
    ${WinedropPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      drop(variables: DropQueryVariables, options?: C): Promise<{data: DropQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DropQueryVariables, query: string}> {
        return requester<{data: DropQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DropQueryVariables, query: string}, DropQueryVariables>(DropDocument, variables, options);
      },
    dropConnection(variables?: DropConnectionQueryVariables, options?: C): Promise<{data: DropConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DropConnectionQueryVariables, query: string}> {
        return requester<{data: DropConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: DropConnectionQueryVariables, query: string}, DropConnectionQueryVariables>(DropConnectionDocument, variables, options);
      },
    winedrop(variables: WinedropQueryVariables, options?: C): Promise<{data: WinedropQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WinedropQueryVariables, query: string}> {
        return requester<{data: WinedropQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WinedropQueryVariables, query: string}, WinedropQueryVariables>(WinedropDocument, variables, options);
      },
    winedropConnection(variables?: WinedropConnectionQueryVariables, options?: C): Promise<{data: WinedropConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WinedropConnectionQueryVariables, query: string}> {
        return requester<{data: WinedropConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: WinedropConnectionQueryVariables, query: string}, WinedropConnectionQueryVariables>(WinedropConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  